//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLogs
    {
        public int id { get; set; }
        public int updateType { get; set; }
        public System.DateTime updatedOn { get; set; }
        public string empName { get; set; }
        public string empNumber { get; set; }
        public int sectionType { get; set; }
        public int userType { get; set; }
        public Nullable<int> statusChange { get; set; }
        public string text { get; set; }
        public int foreignId { get; set; }
        public int requestId { get; set; }
    
        public virtual Requests Requests { get; set; }
    }
}
