//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ancillaries
    {
        public int id { get; set; }
        public Nullable<int> ancillaryProductType { get; set; }
        public string destination { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> excursionDate { get; set; }
        public string excursionName { get; set; }
        public Nullable<int> transferType { get; set; }
        public Nullable<int> insuranceType { get; set; }
        public Nullable<int> passengerNumber { get; set; }
        public Nullable<int> approvalStatus { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public int requestId { get; set; }
    
        public virtual Requests Requests { get; set; }
    }
}
