//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string EmpNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string ManagerEmpNumber { get; set; }
        public System.DateTime SeniorityDate { get; set; }
        public string Organization { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public int Eligibility { get; set; }
        public int IsFullTime { get; set; }
        public int IsSending { get; set; }
        public int Status { get; set; }
        public string Language { get; set; }
    }
}
