//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        public int id { get; set; }
        public Nullable<System.DateTime> departDate { get; set; }
        public string departFrom { get; set; }
        public string departTo { get; set; }
        public string departFlight { get; set; }
        public Nullable<System.DateTime> returnDate { get; set; }
        public string returnFrom { get; set; }
        public string returnTo { get; set; }
        public string returnFlight { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> approvalStatus { get; set; }
        public Nullable<decimal> price { get; set; }
        public int requestId { get; set; }
    
        public virtual Requests Requests { get; set; }
    }
}
