//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassesBalance
    {
        public string employeeNumber { get; set; }
        public string type { get; set; }
        public int used { get; set; }
        public System.DateTime updateDate { get; set; }
        public string status { get; set; }
        public string year { get; set; }
    }
}
