//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passengers
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> typeOfPass { get; set; }
        public string phoneNumber { get; set; }
        public string email { get; set; }
        public Nullable<int> passengerNumber { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> approvalStatus { get; set; }
        public int requestId { get; set; }
    
        public virtual Requests Requests { get; set; }
    }
}
