//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTravel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class STAutomationEntities : DbContext
    {
        public STAutomationEntities()
            : base("name=STAutomationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityLogs> ActivityLogs { get; set; }
        public virtual DbSet<Ancillaries> Ancillaries { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeePassport> EmployeePassports { get; set; }
        public virtual DbSet<Flights> Flights { get; set; }
        public virtual DbSet<Hotels> Hotels { get; set; }
        public virtual DbSet<Notes> Notes { get; set; }
        public virtual DbSet<Passengers> Passengers { get; set; }
        public virtual DbSet<PassesBalance> PassesBalances { get; set; }
        public virtual DbSet<PassesBonus> PassesBonus { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<PassesBonusExpiryDate> PassesBonusExpiryDate { get; set; }
    }
}
