//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTravel.EmailService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="emailObjectClass", Namespace="http://schemas.datacontract.org/2004/07/sunwing.Ens.WcfServices.Common")]
    [System.SerializableAttribute()]
    public partial class emailObjectClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClientIDField;
        
        private string SubjectField;
        
        private string EmailBodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CCToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BodyHtmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StaffTravel.EmailService.emailPriorityItems PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StaffTravel.EmailService.emailTypeItems EmailTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendEmaiAfterTimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIDField, value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string EmailBody {
            get {
                return this.EmailBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailBodyField, value) != true)) {
                    this.EmailBodyField = value;
                    this.RaisePropertyChanged("EmailBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string EmailTo {
            get {
                return this.EmailToField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailToField, value) != true)) {
                    this.EmailToField = value;
                    this.RaisePropertyChanged("EmailTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string CCTo {
            get {
                return this.CCToField;
            }
            set {
                if ((object.ReferenceEquals(this.CCToField, value) != true)) {
                    this.CCToField = value;
                    this.RaisePropertyChanged("CCTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool BodyHtml {
            get {
                return this.BodyHtmlField;
            }
            set {
                if ((this.BodyHtmlField.Equals(value) != true)) {
                    this.BodyHtmlField = value;
                    this.RaisePropertyChanged("BodyHtml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public StaffTravel.EmailService.emailPriorityItems Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public StaffTravel.EmailService.emailTypeItems EmailType {
            get {
                return this.EmailTypeField;
            }
            set {
                if ((this.EmailTypeField.Equals(value) != true)) {
                    this.EmailTypeField = value;
                    this.RaisePropertyChanged("EmailType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string SendEmaiAfterTimestamp {
            get {
                return this.SendEmaiAfterTimestampField;
            }
            set {
                if ((object.ReferenceEquals(this.SendEmaiAfterTimestampField, value) != true)) {
                    this.SendEmaiAfterTimestampField = value;
                    this.RaisePropertyChanged("SendEmaiAfterTimestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="emailPriorityItems", Namespace="http://schemas.datacontract.org/2004/07/sunwing.Ens.WcfServices.Common")]
    public enum emailPriorityItems : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        normal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        high = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        low = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="emailTypeItems", Namespace="http://schemas.datacontract.org/2004/07/sunwing.Ens.WcfServices.Common")]
    public enum emailTypeItems : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        information = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        exception = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        notification = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnsExceptionContainer", Namespace="http://schemas.datacontract.org/2004/07/sunwing.Ens.WcfServices.Common")]
    [System.SerializableAttribute()]
    public partial class EnsExceptionContainer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesssageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Messsage {
            get {
                return this.MesssageField;
            }
            set {
                if ((object.ReferenceEquals(this.MesssageField, value) != true)) {
                    this.MesssageField = value;
                    this.RaisePropertyChanged("Messsage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentJobException", Namespace="http://schemas.datacontract.org/2004/07/sunwing.Ens.BLL.CustomException")]
    [System.SerializableAttribute()]
    public partial class AgentJobException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string emailId {
            get {
                return this.emailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.emailIdField, value) != true)) {
                    this.emailIdField = value;
                    this.RaisePropertyChanged("emailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailService.IEmailService")]
    public interface IEmailService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendEmail", ReplyAction="http://tempuri.org/IEmailService/SendEmailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StaffTravel.EmailService.EnsExceptionContainer), Action="http://tempuri.org/IEmailService/SendEmailEnsExceptionContainerFault", Name="EnsExceptionContainer", Namespace="http://schemas.datacontract.org/2004/07/sunwing.Ens.WcfServices.Common")]
        void SendEmail(StaffTravel.EmailService.emailObjectClass obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/SendEmail", ReplyAction="http://tempuri.org/IEmailService/SendEmailResponse")]
        System.Threading.Tasks.Task SendEmailAsync(StaffTravel.EmailService.emailObjectClass obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/ProcessPendingEmails", ReplyAction="http://tempuri.org/IEmailService/ProcessPendingEmailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StaffTravel.EmailService.EnsExceptionContainer), Action="http://tempuri.org/IEmailService/ProcessPendingEmailsEnsExceptionContainerFault", Name="EnsExceptionContainer", Namespace="http://schemas.datacontract.org/2004/07/sunwing.Ens.WcfServices.Common")]
        StaffTravel.EmailService.AgentJobException[] ProcessPendingEmails(string agentId, System.DateTime requestTimestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailService/ProcessPendingEmails", ReplyAction="http://tempuri.org/IEmailService/ProcessPendingEmailsResponse")]
        System.Threading.Tasks.Task<StaffTravel.EmailService.AgentJobException[]> ProcessPendingEmailsAsync(string agentId, System.DateTime requestTimestamp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmailServiceChannel : StaffTravel.EmailService.IEmailService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailServiceClient : System.ServiceModel.ClientBase<StaffTravel.EmailService.IEmailService>, StaffTravel.EmailService.IEmailService {
        
        public EmailServiceClient() {
        }
        
        public EmailServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendEmail(StaffTravel.EmailService.emailObjectClass obj) {
            base.Channel.SendEmail(obj);
        }
        
        public System.Threading.Tasks.Task SendEmailAsync(StaffTravel.EmailService.emailObjectClass obj) {
            return base.Channel.SendEmailAsync(obj);
        }
        
        public StaffTravel.EmailService.AgentJobException[] ProcessPendingEmails(string agentId, System.DateTime requestTimestamp) {
            return base.Channel.ProcessPendingEmails(agentId, requestTimestamp);
        }
        
        public System.Threading.Tasks.Task<StaffTravel.EmailService.AgentJobException[]> ProcessPendingEmailsAsync(string agentId, System.DateTime requestTimestamp) {
            return base.Channel.ProcessPendingEmailsAsync(agentId, requestTimestamp);
        }
    }
}
